### PR TITLE
Several small fixes

### PR DESCRIPTION
**Pull request by adamretter**
* Website was wrong
* Required eXist-db version was wrong
* Library Module had wrong filename

### CODE REVIEW

**Comment by joewiz** [comment]
@adamretter I'm curious, what's the basis of the requirement for 5.2.0?

**Comment by adamretter** [comment]
Previously the README.md said that you need `5.x`, but that's not a concrete version or a version pattern. So I just chose a version that was above 5.0.0 that I think is relatively stable

**Comment by joewiz** [comment]
Thanks. Ok, the PR looks good to me.

**Comment by joewiz** [comment]
p.s. I also support adopting the convention to use xqm as the file extension of library modules, especially in new projects.

**Comment by adamretter** [comment]
Thanks Joe. It's actually a convention I sought agreement on years ago. I then published it in the eXist-db book. Some have kept to it

**Pull request merged**
